### PR TITLE
Update DatabaseManager.java

### PR DESCRIPTION
**Pull request by Baw-Appie**
Fixed that Korean is not displayed properly

### CODE REVIEW

**Comment by DevLeoko** [comment]
Thanks for contributing :) have you tested these changes?

**Comment by Baw-Appie** [comment]
Yes :)

**Comment by DevLeoko** [comment]
Just noticed that this branch is not from the dev-branch.
Contributions have to be on the development branch sorry

**Comment by DevLeoko** [comment]
@md678685 oh I thought it would screw up the development branch as I can not change the source branch only the target. But it makes sense that it does not as there are no changes in the master that are not in the dev just the other way around it would not work :D

**Pull request merged**
