### PR TITLE
spellcheck take 2 and 3

### PR DESCRIPTION
**Pull request by dutchy1001**
found some more after testing it. Same again with the 2 xml files (something I cant explain)

### CODE REVIEW

**Comment by DevLeoko** [comment]
Sorry I totaly forgot about that Pull-Request

**Comment by dutchy1001** [comment]
lol

**Comment by dutchy1001** [comment]
Have you manual edited the errors or do you want me to look over it again?

**Comment by DevLeoko** [comment]
I'm not sure I think I fixed some of the misspellings but I'm not sure if I found them all :D

**Pull request closed without merging**
