### PR TITLE
Fix for Intern UUID fetcher returning null on join when UUID not cached

### PR DESCRIPTION
**Pull request by james090500**
Fixes issue #322

### CODE REVIEW

**Comment by DevLeoko** [comment]
_fullUUID.toString().replace("-", "");_ introduces UUID processing logic into the Universal class.
All UUID processing logic should be in the UUIDManager, as any other class should not make any assumption about UUIDs other than that they are unique strings used to identify a player.

So the Universal.java class assuming that "-" have to be removed in an issue.

Also, this causes a bug when the UUID fetcher is disabled. (Again this would not happen if UUID logic would be kept in the UUID Manager).

Two possible solutions:
1)
Make a function in the UUIDManager to add UUIDs to the activeUUIDs cache which can be called from the connection listeners or Universal.

2\)
Add a function getUUID(String name, String internalUUID) and move the UUID processing logic to the UUIDManager.

**Comment by james090500** [comment]
Add per requested. I have moved UUID logic to UUIDManaged and from the connection listeners add the uuid and name to cache.

**Comment by james090500** [comment]
Fixed bungee import within UUID Manager

**Comment by DevLeoko** [comment]
This still causes issues with disabled UUID fetcher.

Maybe rather make a method _supplyInternUUID(name, uuid)_ in the UUID Manager, which only adds that UUID to the cache if the mode is set to INTERN or MIXED

**Comment by james090500** [comment]
As requested

**Comment by A248** [comment]
My goodness @DevLeoko ! This looks like the fix to #203 , sitting before our very eyes!

**Comment by DevLeoko** [comment]
No, I don't think that this is related to that issue.
I think all those issues are related to the poor database connection handling we do ^^
See: #320

**Comment by A248** [comment]
It seemed to me rather that we weren't setting the UUID in the parameterised statement, but I could be wrong.

**Pull request merged**
