### PR TITLE
enhanced code readability and fix unclean singleton design pattern

### PR DESCRIPTION
**Pull request by stewue**
Singleton Design Pattern: https://www.tutorialspoint.com/design_pattern/singleton_pattern.htm

### CODE REVIEW

**Comment by stewue** [comment]
Why you did not merge the pull request?

**Comment by DevLeoko** [comment]
As I started a review on this and there has not been any response from you

**Comment by md678685** [comment]
There isn't a review on the PR, it would show up here if there was.

**Comment by DevLeoko** [comment]
http://prntscr.com/fzb6bl
Not sure if I did anything wrong because I've never done a review via GitHub before as I privately only use BitBucket

**Comment by md678685** [comment]
You have to submit the review for it to show up publicly - it's in the top-right of the screen when you're in the "Files changed" view.

**Comment by DevLeoko** [comment]
Okay my bad sorry

**Comment by DevLeoko** [comment]
but I'm not able to reopen it as the repo has been deleted

**Comment by Beelzebu** [comment]
I would like to say that these changes were made in PR #110

**Pull request closed without merging**
