### PR TITLE
Fix compatibility with some chat formatting plugins such as ChatContr…

### PR DESCRIPTION
**Pull request by TheJoshue**
…olPRO and ChatControlRED

### CODE REVIEW

**Comment by TheJoshue** [comment]
If someone do not believe this is an issue, please consider following EXACT steps I described in my issue at https://github.com/DevLeoko/AdvancedBan/issues/589

**Comment by Hopefuls** [comment]
Please refer to my previous comment mentioned on the linked issue:

This may still cause issues with other plugins that still use the `LOWEST` priority. This is due to how Spigot etc handle priorities that are set on the same level. The best way to manage this is to allow administrators to configure which priority they wish to use instead, allowing them to fine-tune and adjust according to the plugins they use.

**Comment by TheJoshue** [comment]
> Please refer to my previous comment mentioned on the linked issue:
> 
> This may still cause issues with other plugins that still use the `LOWEST` priority. This is due to how Spigot etc handle priorities that are set on the same level. The best way to manage this is to allow administrators to configure which priority they wish to use instead, allowing them to fine-tune and adjust according to the plugins they use.

I totally agree, then this is a temporary solution to anyone using CHCPRO/CHCRED
Thanks.

**Comment by DevLeoko** [comment]
Thanks for looking into this, but we will not be merging a "temporary fix" into the master. Especially because canceling the chat event on the LOWEST event priority would suggest that other plugins could just un-cancel the event. Which is not the case for a mute.

I see how HIGHEST priority might give some chat plugins problems if they also want to modify the event and check whether it has been canceled at the same time. So maybe we could switch to event priority HIGH for now. Could you check whether that also fixes the issue @TheJoshue ?

**Comment by TheJoshue** [comment]
> Thanks for looking into this, but we will not be merging a "temporary fix" into the master. Especially because canceling the chat event on the LOWEST event priority would suggest that other plugins could just un-cancel the event. Which is not the case for a mute.
> 
> I see how HIGHEST priority might give some chat plugins problems if they also want to modify the event and check whether it has been canceled at the same time. So maybe we could switch to event priority HIGH for now. Could you check whether that also fixes the issue @TheJoshue ?

I tried with HIGH, it has the same issue when using HIGHEST - message is sent to chat despite player getting deny "you are muted" message.
I tried "NORMAL" EventPriority and it works ok, no issues.

**Comment by PSYCHEER** [comment]
I have a bit another problem :D As AB is using chatlistener at HIGHEST, idk why but I need in CCR priority on MONITOR, but that...not good in long term...some update after 4 years with priority listener? while I don't use any other plugins with chatlistener, it's for me useless to have it on HIGHEST from start :D

**Comment by Hopefuls** [comment]
> Thanks for looking into this, but we will not be merging a "temporary fix" into the master. Especially because canceling the chat event on the LOWEST event priority would suggest that other plugins could just un-cancel the event. Which is not the case for a mute.

**Pull request closed without merging**
